#!/usr/bin/python
# You may redistribute this program and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys;
import os;
from cjdns import cjdns_connect;
import json;
from pprint import pprint;

try:
    adminInfo = open(os.getenv("HOME") + '/.cjdnsadmin', 'r');
except IOError:
    print('Please create a file named .cjdnsadmin in your home directory with');
    print('ip, port, and password of your cjdns engine in json.');
    print('for example:');
    print('{');
    print('    "addr": "127.0.0.1",');
    print('    "port": 11234,');
    print('    "password": "You tell me! (you\'ll find it in your cjdroute.conf)"');
    print('}');
    raise;

data = json.load(adminInfo);
adminInfo.close();

cjdns = cjdns_connect(data['addr'], data['port'], data['password']);
exec 'print(cjdns.' + sys.argv[1] + ')';
