#!/usr/bin/env python2
# You may redistribute this program and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import getopt
import cjdnsadmin.adminTools as at

def main():

    human_readable=False

    try:
        opts, args = getopt.getopt(sys.argv[1:], "h" , ["humanreadable", "help"])
    except getopt.GetoptError, e:
        print(str(e))
        print()
        usage()
        sys.exit(1)

    for o, a in opts:
        if o in ("-h", "--humanreadable"): human_readable=True
        if o == ("--help"):
            usage()
            sys.exit(0)

        

    cjdns=at.anonConnect()
    at.peerStats(cjdns,verbose=True,human_readable=human_readable);
    cjdns.disconnect()


def usage():
    print("usage: peerStats [-h]")
    print("")
    print("     -h, --humanreadable     human readable output of transmitted bytes")
    print("     --help                  this list")
    print("")

main()