#!/usr/bin/env python2
# You may redistribute this program and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from cjdnsadmin.cjdnsadmin import connectWithAdminInfo;

cjdns = connectWithAdminInfo();

i = 0;
while (True):
    search = cjdns.SearchRunner_showActiveSearch(i);
    if ('target' not in search):
        if i != 0: print;
        break;
    print(str(i) + ' tar: ' + search['target'] + '  last asked: ' + search['lastNodeAsked'] +
        '  asked: ' + str(search['totalRequests']) + ' count: ' + str(search['activeSearches']));
    i = i + 1;
