[package]
name = "cjdnstool"
authors = [
    "Ilyas Gasanov <public@gsnoff.com>",
    "Caleb James DeLisle <cjd@cjdns.fr>",
]
version = { workspace = true }
edition = { workspace = true }
description = "Command line tool for querying cjdns admin API."
rust-version = { workspace = true }

[dependencies]
chrono = { workspace = true }
cjdns = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
const_format = { workspace = true }
data-encoding = { workspace = true }
dotenvy = { workspace = true }
env_logger = { workspace = true }
eyre = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
