#!/usr/bin/env bash
# This is a wrapper for ./do that sets architecture variables properly
# I've failed to implement this in debian/rules

export PLATFORM="${DEB_BUILD_ARCH_OS}"
export MARCH="${DEB_HOST_GNU_CPU}"
# work around cjdns being unspecific about x86 compiler targets such as i686
echo "${DEB_HOST_GNU_CPU}" | grep -q 'i.86' && export MARCH="x86"
./do